#!/usr/bin/env python3
"""
check_upstream_updates.py
=========================
Autonomous Upstream Update Monitor for Maverick OS & Agent Harnesses.
Monitors original repositories for all installed skills, hooks, guidelines, and MCPs.
Runs every 3 days via cron or manually on demand.
"""

import os
import sys
import json
import subprocess
from datetime import datetime, timezone

WORKSPACE_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
REGISTRY_PATH = os.path.join(WORKSPACE_ROOT, "configs", "upstream_sources.json")
REPORT_MD_PATH = os.path.join(WORKSPACE_ROOT, "reports", "UPSTREAM_UPDATES.md")
REPORT_JSON_PATH = os.path.join(WORKSPACE_ROOT, "reports", "upstream_updates_report.json")

def get_remote_head(url: str, timeout: int = 15) -> str:
    """Queries remote git repository for HEAD commit SHA via git ls-remote."""
    # Attempt with HTTPS fallback if git@ format
    urls_to_try = [url]
    if url.startswith("git@github.com:"):
        repo_path = url.replace("git@github.com:", "").replace(".git", "")
        urls_to_try.append(f"https://github.com/{repo_path}.git")

    for u in urls_to_try:
        try:
            cmd = ["git", "ls-remote", u, "HEAD"]
            out = subprocess.check_output(cmd, timeout=timeout, stderr=subprocess.DEVNULL).decode("utf-8").strip()
            if out:
                sha = out.split()[0]
                return sha
        except Exception:
            continue

    return ""

def main():
    if not os.path.exists(REGISTRY_PATH):
        print(f"Error: Registry not found at {REGISTRY_PATH}", file=sys.stderr)
        sys.exit(1)

    with open(REGISTRY_PATH, "r", encoding="utf-8") as f:
        registry = json.load(f)

    sources = registry.get("sources", [])
    now_iso = datetime.now(timezone.utc).isoformat()
    
    print("=" * 70)
    print(f"[{now_iso}] CHECKING UPSTREAM UPDATES FOR SKILLS, HOOKS & GUIDELINES")
    print(f"Total Sources Monitored: {len(sources)}")
    print("=" * 70)

    results = []
    updates_found = 0
    baselined_count = 0
    up_to_date_count = 0
    unreachable_count = 0

    for source in sources:
        sid = source.get("id")
        name = source.get("name")
        repo = source.get("repo")
        url = source.get("url")
        category = source.get("category", "skills")
        last_sha = source.get("last_checked_sha", "")

        remote_sha = get_remote_head(url)
        
        status = "UNKNOWN"
        diff_info = ""

        if not remote_sha:
            status = "UNREACHABLE"
            unreachable_count += 1
            print(f"[!] {name:40} | UNREACHABLE ({repo})")
        elif not last_sha:
            status = "BASELINED"
            source["last_checked_sha"] = remote_sha
            source["last_checked_at"] = now_iso
            baselined_count += 1
            print(f"[*] {name:40} | BASELINED -> {remote_sha[:10]}")
        elif last_sha != remote_sha:
            status = "UPDATE_AVAILABLE"
            updates_found += 1
            source["previous_sha"] = last_sha
            source["last_checked_sha"] = remote_sha
            source["last_checked_at"] = now_iso
            diff_info = f"Update detected: {last_sha[:8]} -> {remote_sha[:8]}"
            print(f"[+] {name:40} | UPDATE AVAILABLE ({last_sha[:8]} -> {remote_sha[:8]})")
        else:
            status = "UP_TO_DATE"
            source["last_checked_at"] = now_iso
            up_to_date_count += 1
            print(f"[=] {name:40} | UP TO DATE ({remote_sha[:10]})")

        results.append({
            "id": sid,
            "name": name,
            "category": category,
            "repo": repo,
            "url": url,
            "status": status,
            "local_sha": last_sha,
            "remote_sha": remote_sha,
            "checked_at": now_iso,
            "diff_info": diff_info,
            "local_targets": source.get("local_targets", [])
        })

    # Save updated registry
    registry["last_run_at"] = now_iso
    registry["summary"] = {
        "total": len(sources),
        "updates_available": updates_found,
        "up_to_date": up_to_date_count,
        "baselined": baselined_count,
        "unreachable": unreachable_count
    }
    with open(REGISTRY_PATH, "w", encoding="utf-8") as f:
        json.dump(registry, f, indent=2)

    # Save JSON report
    with open(REPORT_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump({
            "generated_at": now_iso,
            "summary": registry["summary"],
            "results": results
        }, f, indent=2)

    # Generate Markdown Report
    md_lines = [
        "# Upstream Source Audit & Update Report",
        f"<!-- Automatically generated by scripts/check_upstream_updates.py -->",
        f"**Last Scanned:** `{now_iso}`  ",
        f"**Cadence:** Every 3 Days via System Crontab (`0 3 */3 * *`)  ",
        "",
        "## Summary Metrics",
        f"- **Total Tracked Repositories:** `{len(sources)}`",
        f"- **Updates Available:** `{updates_found}`",
        f"- **Up to Date:** `{up_to_date_count}`",
        f"- **Newly Baselined:** `{baselined_count}`",
        f"- **Unreachable / Network Blocked:** `{unreachable_count}`",
        "",
        "---",
        "",
        "## Audit Breakdown by Category",
        ""
    ]

    for cat in ["skills", "hooks", "guidelines", "mcp"]:
        cat_items = [r for r in results if r["category"] == cat]
        if not cat_items:
            continue
        md_lines.append(f"### {cat.upper()} ({len(cat_items)} tracked)")
        md_lines.append("| Name | Repository | Status | Latest Commit | Local Targets |")
        md_lines.append("| :--- | :--- | :--- | :--- | :--- |")
        for item in cat_items:
            badge = "🟢 Up to Date"
            if item["status"] == "UPDATE_AVAILABLE":
                badge = "🔴 **Update Available**"
            elif item["status"] == "BASELINED":
                badge = "🟡 Baselined"
            elif item["status"] == "UNREACHABLE":
                badge = "⚪ Unreachable"
            
            sha_str = f"`{item['remote_sha'][:8]}`" if item['remote_sha'] else "N/A"
            targets_str = "<br>".join([f"`{t}`" for t in item["local_targets"][:2]])
            md_lines.append(f"| **{item['name']}** | [{item['repo']}]({item['url'].replace('.git', '')}) | {badge} | {sha_str} | {targets_str} |")
        md_lines.append("")

    with open(REPORT_MD_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(md_lines))

    print("=" * 70)
    print(f"AUDIT COMPLETE: {updates_found} updates | {up_to_date_count} up-to-date | {baselined_count} baselined | {unreachable_count} unreachable")
    print(f"Report written to: {REPORT_MD_PATH}")
    print("=" * 70)

if __name__ == "__main__":
    main()
